version : '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: 159.203.159.107
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 80:80